name: Phils3rs Blog
description: Persönlicher Blog rund ums Thema Linux, Software kompilieren, Hardware Modding und Politik
markdown: redcarpet
baseurl: ""
url: "https://blog.phils3r.de"
encoding: "utf-8"
paginate: 8
timezone: Europe/Berlin
paginate_path: "/page:num/"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
